/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import { languages } from 'monaco-editor/esm/vs/editor/editor.api';

export const StreamingHighlightConfig = <languages.IMonarchLanguage>{
    tokenPostfix: '.asaql',
    ignoreCase: true,

    brackets: [
        { open: '[', close: ']', token: 'delimiter.square' },
        { open: '(', close: ')', token: 'delimiter.parenthesis' },
    ],
 
    ReservedKeywords: [
        'ADD',
        'AFTER',
        'ALL',
        'ALTER',
        'AND',
        'ANY',
        'APPLY',
        'AS',
        'ASC',
        'AUTHORIZATION',
        'BACKUP',
        'BEGIN',
        'BETWEEN',
        'BREAK',
        'BROWSE',
        'BULK',
        'BY',
        'CASCADE',
        'CASE',
        'CHECK',
        'CHECKPOINT',
        'CLOSE',
        'CLUSTERED',
        'COLLATE',
        'COLUMN',
        'COMMIT',
        'COMPUTE',
        'CONSTRAINT',
        'CONTAINS',
        'CONTAINSTABLE',
        'CONTINUE',
        'CONVERT',
        'CREATE',
        'CROSS',
        'CURRENT',
        'CURRENT_DATE',
        'CURRENT_TIME',
        'CURRENT_TIMESTAMP',
        'CURRENT_USER',
        'CURSOR',
        'DATABASE',
        'DBCC',
        'DEALLOCATE',
        'DECLARE',
        'DEFAULT',
        'DELETE',
        'DENY',
        'DESC',
        'DISTINCT',
        'DISTRIBUTED',
        'DOUBLE',
        'DROP',
        'DURATION',
        'ELSE',
        'END',
        'ERRLVL',
        'ESCAPE',
        'EXCEPT',
        'EXEC',
        'EXECUTE',
        'EXISTS',
        'EXIT',
        'FETCH',
        'FILE',
        'FILLFACTOR',
        'FOR',
        'FOREIGN',
        'FREETEXT',
        'FREETEXTTABLE',
        'FROM',
        'FULL',
        'FUNCTION',
        'GOTO',
        'GRANT',
        'GROUP',
        'GROUP',
        'HAVING',
        'HOLDLOCK',
        'IDENTITY',
        'IDENTITY_INSERT',
        'IDENTITYCOL',
        'IDENTITY_INSERT',
        'IF',
        'IN',
        'INDEX',
        'INNER',
        'INSERT',
        'INTERSECT',
        'INTO',
        'IS',
        'LIMIT',
        'JOIN',
        'KEY',
        'KILL',
        'LEFT',
        'LIKE',
        'LINENO',
        'MATCH',
        'MATCH_RECOGNIZE',
        'MEASURES',
        'NATIONAL',
        'NEXT',
        'NOCHECK',
        'NONCLUSTERED',
        'NOT',
        'NULL',
        'NULLIF',
        'OF',
        'OFF',
        'OFFSETS',
        'ON',
        'OPEN',
        'OPENDATASOURCE',
        'OPENQUERY',
        'OPENROWSET',
        'OPENXML',
        'OPTION',
        'OR',
        'ORDER',
        'OUTER',
        'OVER',
        'PARTITION',
        'PATTERN',
        'PERCENT',
        'PLAN',
        'PRIMARY',
        'PRINT',
        'PROC',
        'PROCEDURE',
        'PUBLIC',
        'RAISERROR',
        'READ',
        'READTEXT',
        'RECONFIGURE',
        'REFERENCES',
        'REPLICATION',
        'RESTORE',
        'RESTRICT',
        'RETURN',
        'REVOKE',
        'RIGHT',
        'ROLLBACK',
        'ROW',
        'ROWCOUNT',
        'ROWGUIDCOL',
        'RULE',
        'SAVE',
        'SCHEMA',
        'SELECT',
        'SESSION_USER',
        'SET',
        'SETUSER',
        'SHUTDOWN',
        'SKIP',
        'SOME',
        'STATISTICS',
        'SYSTEM',
        'SYSTEM_USER',
        'TABLE',
        'TEXTSIZE',
        'THEN',
        'TIMESTAMP',
        'TO',
        'TOP',
        'TRAN',
        'TRANSACTION',
        'TRIGGER',
        'TRUNCATE',
        'TRY_CONVERT',
        'TSEQUAL',
        'UNION',
        'UNIQUE',
        'UPDATE',
        'UPDATETEXT',
        'USE',
        'USER',
        'VALUES',
        'VARYING',
        'VIEW',
        'WAITFOR',
        'WHEN',
        'WHERE',
        'WHILE',
        'WINDOW',
        'WITH',
        'WITHIN',
        'WRITETEXT',
    ],

    timeManagement: [
        'UDA', 'UDF', 'day', 'hour', 'minute', 'second', 'millisecond', 'microsecond', 'Duration', 'Hop', 'Offset'
    ],

    builtinFunctions: [
        // Aggregate functions
        'AVG', 'COALESCE', 'COUNT', 'Collect', 'CollectTOP', 'MAX', 'MIN', 'Percentile_Cont', 'Percentile_Disc', 'STDEV', 'STDEVP', 'SUM', 'TopOne', 'VAR', 'VARP', 'STRING_AGG',
        // Analytic functions
        'AnomalyDetection_SpikeAndDip', 'AnomalyDetection_ChangePoint', 'ISFIRST', 'FIRST', 'LAG', 'LAST',
        // Array functions
        'GetArrayElement', 'GetArrayElements', 'GetArrayLength',
        // Conversion functions
        'CAST', 'TRY_CAST', 'GetType',
        // Date and time functions
        'DATENAME', 'DATEPART', 'DAY', 'MONTH', 'YEAR', 'DATETIMEFROMPARTS', 'DATEDIFF', 'DATEADD', 'EOMONTH', 'ISDATE',
        // GeoSpatial functions
        'CreatePoint', 'CreatePolygon', 'CreateLineString', 'ST_DISTANCE', 'ST_INTERSECTS', 'ST_OVERLAPS', 'ST_WITHIN',
        // Input metadata functions
        'GetMetadataPropertyValue',
        // Mathematical functions
        'ABS', 'CEILING', 'EXP', 'FLOOR', 'POWER', 'ROUND', 'SIGN', 'SQUARE', 'SQRT', 'ACOS', 'ASIN', 'ATAN', 'ATN2', 'COS', 'COT', 'SIN', 'TAN', 'DEGREES', 'RADIANS', 'PI', 'LOG', 'LOG10',
        // Record functions
        'GetRecordProperties', 'GetRecordPropertyValue',
        // String functions
        'CHARINDEX', 'CONCAT', 'CONCAT_WS', 'LEN', 'LEFT', 'LTRIM', 'LOWER', 'NCHAR', 'PATINDEX', 'REGEXMATCH', 'REPLACE', 'REPLICATE', 'REVERSE', 'RIGHT', 'RTRIM', 'SPACE', 'STUFF', 'TRANSLATE', 'TRIM', 'SUBSTRING', 'UNICODE', 'UPPER', 'ISJSON', 'JSON_VALUE', 'JSON_QUERY', 'JSON_MODIFY',
        // Windowing functions
        'Window', 'Windows', 'TumblingWindow', 'HoppingWindow', 'SlidingWindow', 'SessionWindow', 'Tumbling', 'Hopping', 'Sliding', 'Session',
    ],
    
    builtinDataTypes: [
        'bigint', 'decimal', 'float', 'datetime', 'record', 'array', 'bit', 'nvarchar', 'varbinary'
    ],

    tokenizer: {
        root: [
            { include: '@comments' },
            { include: '@whitespace' },
            { include: '@numbers' },
            { include: '@strings' },
            { include: '@complexIdentifiers' },
            { include: '@scopes' },
            [/[;,.]/, 'delimiter'],
            [/[()]/, '@brackets'],
            [/[\w@#$]+/, {
                cases: {
                    '@ReservedKeywords': 'keyword',
                    '@timeManagement': 'keyword',
                    '@builtinDataTypes': 'variable.predefined',
                    '@builtinFunctions': 'key',
                    '@default': 'identifier',
                },
            }],
            [/[<>=!%&+\-*/|~^]/, 'operator'],
        ],
        whitespace: [[/\s+/, 'white']],
        comments: [
            [/--+.*/, 'comment'],
            [/\/\*/, { token: 'comment.quote', next: '@comment' }],
        ],
        comment: [
            [/[^*/]+/, 'comment'],
            // Not supporting nested comments, as nested comments seem to not be standard?
            // i.e. http://stackoverflow.com/questions/728172/are-there-multiline-comment-delimiters-in-sql-that-are-vendor-agnostic
            // [/\/\*/, { token: 'comment.quote', next: '@push' }],    // nested comment not allowed :-(
            [/\*\//, { token: 'comment.quote', next: '@pop' }],
            [/./, 'comment'],
        ],
        numbers: [
            [/0[xX][0-9a-fA-F]*/, 'number'],
            [/[$][+-]*\d*(\.\d*)?/, 'number'],
            [/((\d+(\.\d*)?)|(\.\d+))([eE][-+]?\d+)?/, 'number'],
        ],
        strings: [
            [/N'/, { token: 'string', next: '@string' }],
            [/'/, { token: 'string', next: '@string' }],
        ],
        string: [
            [/[^']+/, 'string'],
            [/''/, 'string'],
            [/'/, { token: 'string', next: '@pop' }],
        ],
        complexIdentifiers: [
            [/\[/, { token: 'identifier.quote', next: '@bracketedIdentifier' }],
            [/"/, { token: 'identifier.quote', next: '@quotedIdentifier' }],
        ],
        bracketedIdentifier: [
            [/[^\]]+/, 'identifier.quote'],
            [/]]/, 'identifier.quote'],
            [/]/, { token: 'identifier.quote', next: '@pop' }],
        ],
        quotedIdentifier: [
            [/[^"]+/, 'identifier.quote'],
            [/""/, 'identifier.quote'],
            [/"/, { token: 'identifier.quote', next: '@pop' }],
        ],
        scopes: [
            [/CASE\b/i, { token: 'keyword.case' }],
            [/END\b/i, { token: 'keyword.case' }],
        ],
    },
};
