/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import * as monaco from 'monaco-editor';

export const sqlComputeMonarchRule = <monaco.languages.IMonarchLanguage>{
    defaultToken: '',
    tokenPostfix: '.sqlcompute',
    ignoreCase: true,

    brackets: [
        { open: '[', close: ']', token: 'delimiter.square' },
        { open: '(', close: ')', token: 'delimiter.parenthesis' }
    ],

    ReservedKeywords: [
        'ADD',
        'ALL',
        'ALTER',
        'AND',
        'ANY',
        'AS',
        'ASC',
        'AUTHORIZATION',
        'BACKUP',
        'BEGIN',
        'BETWEEN',
        'BREAK',
        'BROWSE',
        'BULK',
        'BY',
        'CASCADE',
        'CASE',
        'CHECK',
        'CHECKPOINT',
        'CLOSE',
        'CLUSTERED',
        'COLLATE',
        'COLUMN',
        'COMMIT',
        'COMPUTE',
        'CONSTRAINT',
        'CONTAINS',
        'CONTAINSTABLE',
        'CONTINUE',
        'CONVERT',
        'CREATE',
        'CROSS',
        'CURRENT',
        'CURSOR',
        'DATABASE',
        'DBCC',
        'DEALLOCATE',
        'DECLARE',
        'DEFAULT',
        'DELETE',
        'DENY',
        'DESC',
        'DISK',
        'DISTINCT',
        'DISTRIBUTED',
        'DOUBLE',
        'DROP',
        'DUMP',
        'ELSE',
        'END',
        'ERRLVL',
        'ESCAPE',
        'EXCEPT',
        'EXEC',
        'EXECUTE',
        'EXISTS',
        'EXIT',
        'EXTERNAL',
        'FETCH',
        'FILE',
        'FILLFACTOR',
        'FOR',
        'FOREIGN',
        'FREETEXT',
        'FREETEXTTABLE',
        'FROM',
        'FULL',
        'FUNCTION',
        'GOTO',
        'GRANT',
        'GROUP',
        'GROUP',
        'HAVING',
        'HOLDLOCK',
        'IDENTITY',
        'IDENTITYCOL',
        'IDENTITY_INSERT',
        'IF',
        'IN',
        'INDEX',
        'INNER',
        'INSERT',
        'INTERSECT',
        'INTO',
        'IS',
        'JOIN',
        'KEY',
        'KILL',
        'LEFT',
        'LIKE',
        'LINENO',
        'LOAD',
        'MERGE',
        'NATIONAL',
        'NOCHECK',
        'NONCLUSTERED',
        'NOT',
        'NULL',
        'OF',
        'OFF',
        'OFFSETS',
        'ON',
        'OPEN',
        'OPENDATASOURCE',
        'OPENQUERY',
        'OPENROWSET',
        'OPENXML',
        'OPTION',
        'OR',
        'ORDER',
        'OUTER',
        'OVER',
        'PERCENT',
        'PIVOT',
        'PLAN',
        'PRECISION',
        'PRIMARY',
        'PRINT',
        'PROC',
        'PROCEDURE',
        'PUBLIC',
        'RAISERROR',
        'READ',
        'READTEXT',
        'RECONFIGURE',
        'REFERENCES',
        'REPLICATION',
        'RESTORE',
        'RESTRICT',
        'RETURN',
        'REVERT',
        'REVOKE',
        'RIGHT',
        'ROLLBACK',
        'ROWCOUNT',
        'ROWGUIDCOL',
        'RULE',
        'SAVE',
        'SCHEMA',
        'SECURITYAUDIT',
        'SELECT',
        'SEMANTICKEYPHRASETABLE',
        'SEMANTICSIMILARITYDETAILSTABLE',
        'SEMANTICSIMILARITYTABLE',
        'SET',
        'SETUSER',
        'SHUTDOWN',
        'SOME',
        'STATISTICS',
        'TABLE',
        'TABLESAMPLE',
        'TEXTSIZE',
        'THEN',
        'TO',
        'TOP',
        'TRAN',
        'TRANSACTION',
        'TRIGGER',
        'TRUNCATE',
        'TRY_CONVERT',
        'TSEQUAL',
        'UNION',
        'UNIQUE',
        'UNPIVOT',
        'UPDATE',
        'UPDATETEXT',
        'USE',
        'USER',
        'VALUES',
        'VARYING',
        'VIEW',
        'WAITFOR',
        'WHEN',
        'WHERE',
        'WHILE',
        'WITH',
        'WITHIN',
        'WRITETEXT'
    ],

    ODBCReservedKeywords: [
        'ABSOLUTE',
        'ACTION',
        'ADA',
        'ADD',
        'ALL',
        'ALLOCATE',
        'ALTER',
        'AND',
        'ANY',
        'ARE',
        'AS',
        'ASC',
        'ASSERTION',
        'AT',
        'AUTHORIZATION',
        'BEGIN',
        'BETWEEN',
        'BIT',
        'BOTH',
        'BY',
        'CASCADE',
        'CASCADED',
        'CASE',
        'CAST',
        'CATALOG',
        'CHAR',
        'CHARACTER',
        'CHARACTER_LENGTH',
        'CHAR_LENGTH',
        'CHECK',
        'CLOSE',
        'COLLATE',
        'COLLATION',
        'COLUMN',
        'COMMIT',
        'CONNECT',
        'CONNECTION',
        'CONSTRAINT',
        'CONSTRAINTS',
        'CONTINUE',
        'CONVERT',
        'CORRESPONDING',
        'CREATE',
        'CROSS',
        'CURRENT',
        'CURSOR',
        'DATE',
        'DEALLOCATE',
        'DEC',
        'DECIMAL',
        'DECLARE',
        'DEFAULT',
        'DEFERRABLE',
        'DEFERRED',
        'DELETE',
        'DESC',
        'DESCRIBE',
        'DESCRIPTOR',
        'DIAGNOSTICS',
        'DISCONNECT',
        'DISTINCT',
        'DOMAIN',
        'DOUBLE',
        'DROP',
        'ELSE',
        'END',
        'END-EXEC',
        'ESCAPE',
        'EXCEPT',
        'EXCEPTION',
        'EXEC',
        'EXECUTE',
        'EXISTS',
        'EXTERNAL',
        'EXTRACT',
        'FALSE',
        'FETCH',
        'FIRST',
        'FLOAT',
        'FOR',
        'FOREIGN',
        'FORTRAN',
        'FOUND',
        'FROM',
        'FULL',
        'GET',
        'GLOBAL',
        'GO',
        'GOTO',
        'GRANT',
        'GROUP',
        'HAVING',
        'IDENTITY',
        'IMMEDIATE',
        'IN',
        'INCLUDE',
        'INDEX',
        'INDICATOR',
        'INITIALLY',
        'INNER',
        'INSENSITIVE',
        'INSERT',
        'INT',
        'INTEGER',
        'INTERSECT',
        'INTERVAL',
        'INTO',
        'IS',
        'ISOLATION',
        'JOIN',
        'KEY',
        'LANGUAGE',
        'LAST',
        'LEADING',
        'LEFT',
        'LEVEL',
        'LIKE',
        'LOCAL',
        'MATCH',
        'MAX',
        'MIN',
        'MODULE',
        'NAMES',
        'NATIONAL',
        'NATURAL',
        'NCHAR',
        'NEXT',
        'NO',
        'NONE',
        'NOT',
        'NULL',
        'NUMERIC',
        'OF',
        'ON',
        'ONLY',
        'OPEN',
        'OPTION',
        'OR',
        'ORDER',
        'OUTER',
        'OVERLAPS',
        'PAD',
        'PARTIAL',
        'PASCAL',
        'POSITION',
        'PRECISION',
        'PREPARE',
        'PRESERVE',
        'PRIMARY',
        'PRIOR',
        'PRIVILEGES',
        'PROCEDURE',
        'PUBLIC',
        'READ',
        'REAL',
        'REFERENCES',
        'RELATIVE',
        'RESTRICT',
        'REVOKE',
        'RIGHT',
        'ROLLBACK',
        'ROWS',
        'SCHEMA',
        'SCROLL',
        'SECTION',
        'SELECT',
        'SESSION',
        'SET',
        'SIZE',
        'SMALLINT',
        'SOME',
        'SQL',
        'SQLCA',
        'SQLCODE',
        'SQLERROR',
        'SQLSTATE',
        'SQLWARNING',
        'TABLE',
        'TEMPORARY',
        'THEN',
        'TIME',
        'TIMESTAMP',
        'TIMEZONE_HOUR',
        'TIMEZONE_MINUTE',
        'TO',
        'TRAILING',
        'TRANSACTION',
        'TRANSLATE',
        'TRANSLATION',
        'TRIM',
        'TRUE',
        'UNION',
        'UNIQUE',
        'UNKNOWN',
        'UPDATE',
        'USAGE',
        'USER',
        'USING',
        'VALUE',
        'VALUES',
        'VARCHAR',
        'VARYING',
        'VIEW',
        'WHEN',
        'WHENEVER',
        'WHERE',
        'WITH',
        'WORK',
        'WRITE',
        'ZONE'
    ],

    FutureKeywords: [
        'ABSOLUTE',
        'ACTION',
        'ADMIN',
        'AFTER',
        'AGGREGATE',
        'ALIAS',
        'ALLOCATE',
        'ARE',
        'ARRAY',
        'ASENSITIVE',
        'ASSERTION',
        'ASYMMETRIC',
        'AT',
        'ATOMIC',
        'BEFORE',
        'BINARY',
        'BIT',
        'BLOB',
        'BOOLEAN',
        'BOTH',
        'BREADTH',
        'CALL',
        'CALLED',
        'CARDINALITY',
        'CASCADED',
        'CAST',
        'CATALOG',
        'CHAR',
        'CHARACTER',
        'CLASS',
        'CLOB',
        'COLLATION',
        'COLLECT',
        'COMPLETION',
        'CONDITION',
        'CONNECT',
        'CONNECTION',
        'CONSTRAINTS',
        'CONSTRUCTOR',
        'CORR',
        'CORRESPONDING',
        'COVAR_POP',
        'COVAR_SAMP',
        'CUBE',
        'CURRENT_CATALOG',
        'CURRENT_DEFAULT_TRANSFORM_GROUP',
        'CURRENT_PATH',
        'CURRENT_ROLE',
        'CURRENT_SCHEMA',
        'CURRENT_TRANSFORM_GROUP_FOR_TYPE',
        'CYCLE',
        'DATA',
        'DATE',
        'DEC',
        'DECIMAL',
        'DEFERRABLE',
        'DEFERRED',
        'DEPTH',
        'DEREF',
        'DESCRIBE',
        'DESCRIPTOR',
        'DESTROY',
        'DESTRUCTOR',
        'DETERMINISTIC',
        'DIAGNOSTICS',
        'DICTIONARY',
        'DISCONNECT',
        'DOMAIN',
        'DYNAMIC',
        'EACH',
        'ELEMENT',
        'END-EXEC',
        'EQUALS',
        'EVERY',
        'EXCEPTION',
        'FALSE',
        'FILTER',
        'FIRST',
        'FLOAT',
        'FOUND',
        'FREE',
        'FULLTEXTTABLE',
        'FUSION',
        'GENERAL',
        'GET',
        'GLOBAL',
        'GO',
        'HOLD',
        'HOST',
        'IGNORE',
        'IMMEDIATE',
        'INDICATOR',
        'INITIALIZE',
        'INITIALLY',
        'INOUT',
        'INPUT',
        'INT',
        'INTEGER',
        'INTERSECTION',
        'INTERVAL',
        'ISOLATION',
        'ITERATE',
        'LANGUAGE',
        'LARGE',
        'LAST',
        'LATERAL',
        'LEADING',
        'LESS',
        'LEVEL',
        'LIKE_REGEX',
        'LIMIT',
        'LN',
        'LOCAL',
        'LOCALTIME',
        'LOCALTIMESTAMP',
        'LOCATOR',
        'MAP',
        'MATCH',
        'MEMBER',
        'METHOD',
        'MOD',
        'MODIFIES',
        'MODIFY',
        'MODULE',
        'MULTISET',
        'NAMES',
        'NATURAL',
        'NCHAR',
        'NCLOB',
        'NEW',
        'NEXT',
        'NO',
        'NONE',
        'NORMALIZE',
        'NUMERIC',
        'OBJECT',
        'OCCURRENCES_REGEX',
        'OLD',
        'ONLY',
        'OPERATION',
        'ORDINALITY',
        'OUT',
        'OUTPUT',
        'OVERLAY',
        'PAD',
        'PARAMETER',
        'PARAMETERS',
        'PARTIAL',
        'PARTITION',
        'PATH',
        'POSITION_REGEX',
        'POSTFIX',
        'PREFIX',
        'PREORDER',
        'PREPARE',
        'PRESERVE',
        'PRIOR',
        'PRIVILEGES',
        'RANGE',
        'READS',
        'REAL',
        'RECURSIVE',
        'REF',
        'REFERENCING',
        'REGR_AVGX',
        'REGR_AVGY',
        'REGR_COUNT',
        'REGR_INTERCEPT',
        'REGR_R2',
        'REGR_SLOPE',
        'REGR_SXX',
        'REGR_SXY',
        'REGR_SYY',
        'RELATIVE',
        'RELEASE',
        'RESULT',
        'RETURNS',
        'ROLE',
        'ROLLUP',
        'ROUTINE',
        'ROW',
        'ROWS',
        'SAVEPOINT',
        'SCOPE',
        'SCROLL',
        'SEARCH',
        'SECTION',
        'SENSITIVE',
        'SEQUENCE',
        'SESSION',
        'SETS',
        'SIMILAR',
        'SIZE',
        'SMALLINT',
        'SPECIFIC',
        'SPECIFICTYPE',
        'SQL',
        'SQLEXCEPTION',
        'SQLSTATE',
        'SQLWARNING',
        'START',
        'STATE',
        'STATEMENT',
        'STATIC',
        'STDDEV_POP',
        'STDDEV_SAMP',
        'STRUCTURE',
        'SUBMULTISET',
        'SUBSTRING_REGEX',
        'SYMMETRIC',
        'SYSTEM',
        'TEMPORARY',
        'TERMINATE',
        'THAN',
        'TIME',
        'TIMESTAMP',
        'TIMEZONE_HOUR',
        'TIMEZONE_MINUTE',
        'TRAILING',
        'TRANSLATE_REGEX',
        'TRANSLATION',
        'TREAT',
        'TRUE',
        'UESCAPE',
        'UNDER',
        'UNKNOWN',
        'UNNEST',
        'USAGE',
        'USING',
        'VALUE',
        'VARCHAR',
        'VARIABLE',
        'VAR_POP',
        'VAR_SAMP',
        'WHENEVER',
        'WIDTH_BUCKET',
        'WINDOW',
        'WITHIN',
        'WITHOUT',
        'WORK',
        'WRITE',
        'XMLAGG',
        'XMLATTRIBUTES',
        'XMLBINARY',
        'XMLCAST',
        'XMLCOMMENT',
        'XMLCONCAT',
        'XMLDOCUMENT',
        'XMLELEMENT',
        'XMLEXISTS',
        'XMLFOREST',
        'XMLITERATE',
        'XMLNAMESPACES',
        'XMLPARSE',
        'XMLPI',
        'XMLQUERY',
        'XMLSERIALIZE',
        'XMLTABLE',
        'XMLTEXT',
        'XMLVALIDATE',
        'ZONE'
    ],

    operators: [
        // Other operators are already in keyword list. So only keep these two in this list.
        'APPLY',
        'MATCHED'
    ],
    builtinFunctions: [
        'ABS',
        'ACOS',
        'APPROX_COUNT_DISTINCT',
        'ASCII',
        'ASIN',
        'ATAN',
        'ATN2',
        'AVG',
        'BINARY_CHECKSUM',
        'BIT_LENGTH',
        'CEILING',
        'CHARINDEX',
        'CHECKSUM',
        'COALESCE',
        'COLLATIONPROPERTY',
        'COL_NAME',
        'CONCAT',
        'COS',
        'COT',
        'COUNT',
        'COUNT_BIG',
        'CUME_DIST',
        'CURDATE',
        'CURRENT_DATE',
        'CURRENT_TIME',
        'CURRENT_TIMESTAMP',
        'CURRENT_USER',
        'CURTIME',
        'DATABASEPROPERTYEX',
        'DATALENGTH',
        'DATEADD',
        'DATEDIFF',
        'DATEFROMPARTS',
        'DATENAME',
        'DATEPART',
        'DATETIME2FROMPARTS',
        'DATETIMEFROMPARTS',
        'DATETIMEOFFSETFROMPARTS',
        'DAY',
        'DAYNAME',
        'DAYOFMONTH',
        'DAYOFWEEK',
        'DB_ID',
        'DB_NAME',
        'DEGREES',
        'DENSE_RANK',
        'DIFFERENCE',
        'EOMONTH',
        'ERROR_MESSAGE',
        'ERROR_NUMBER',
        'ERROR_PROCEDURE',
        'ERROR_SEVERITY',
        'ERROR_STATE',
        'EXP',
        'FIRST_VALUE',
        'FLOOR',
        'GETDATE',
        'GETUTCDATE',
        'GROUPING',
        'HASHBYTES',
        'HAS_DBACCESS',
        'HOUR',
        'INDEXPROPERTY',
        'ISDATE',
        'ISNULL',
        'ISNUMERIC',
        'LAG',
        'LAST_VALUE',
        'LEAD',
        'LEN',
        'LOG10',
        'LOWER',
        'LTRIM',
        'MINUTE',
        'MONTH',
        'MONTHNAME',
        'NTILE',
        'NULLIF',
        'OBJECTPROPERTY',
        'OBJECTPROPERTYEX',
        'OBJECT_ID',
        'OBJECT_NAME',
        'OCTET_LENGTH',
        'PARSENAME',
        'PATINDEX',
        'PERCENTILE_CONT',
        'PERCENTILE_DISC',
        'PERCENT_RANK',
        'PI',
        'POWER',
        'QUARTER',
        'QUOTENAME',
        'RADIANS',
        'RAND',
        'RANK',
        'REPLACE',
        'REVERSE',
        'ROUND',
        'ROW_NUMBER',
        'RTRIM',
        'SCHEMA_ID',
        'SCHEMA_NAME',
        'SECOND',
        'SERVERPROPERTY',
        'SESSION_USER',
        'SIGN',
        'SIN',
        'SMALLDATETIMEFROMPARTS',
        'SOUNDEX',
        'SPACE',
        'SQL_VARIANT_PROPERTY',
        'SQRT',
        'SQUARE',
        'STATS_DATE',
        'STDEV',
        'STDEVP',
        'STR',
        'STRING_AGG',
        'STUFF',
        'SUBSTRING',
        'SUM',
        'SUSER_SNAME',
        'SWITCHOFFSET',
        'SYSDATETIME',
        'SYSDATETIMEOFFSET',
        'SYSTEM_USER',
        'SYSUTCDATETIME',
        'TAN',
        'TERTIARY_WEIGHTS',
        'TIMEFROMPARTS',
        'TODATETIMEOFFSET',
        'TYPEPROPERTY',
        'TYPE_ID',
        'TYPE_NAME',
        'UNICODE',
        'UPPER',
        'USER_NAME',
        'VAR',
        'VARP',
        'WEEK',
        'XACT_STATE',
        'YEAR'
    ],
    builtinVariables: [
        '@@DATEFIRST',
        '@@ERROR',
        '@@LANGUAGE',
        '@@SPID',
        '@@TRANCOUNT',
        '@@VERSION'
    ],
    tokenizer: {
        root: [
            { include: '@comments' },
            { include: '@whitespace' },
            { include: '@pseudoColumns' },
            { include: '@numbers' },
            { include: '@strings' },
            { include: '@complexIdentifiers' },
            { include: '@scopes' },
            [/[;,.]/, 'delimiter'],
            [/[()]/, '@brackets'],
            [/[\w@#$]+/, {
                cases: {
                    '@ReservedKeywords': 'keyword',
                    '@ODBCReservedKeywords': 'keyword',
                    '@FutureKeywords': 'keyword',
                    '@operators': 'keyword',
                    '@builtinVariables': 'variable.predefined',
                    '@builtinFunctions': 'key',
                    '@default': 'identifier'
                }
            }],
            [/[<>=!%&+\-*/|~^]/, 'operator']
        ],
        whitespace: [
            [/\s+/, 'white']
        ],
        comments: [
            [/--+.*/, 'comment'],
            [/\/\*/, { token: 'comment.quote', next: '@comment' }]
        ],
        comment: [
            [/[^*/]+/, 'comment'],
            // Not supporting nested comments, as nested comments seem to not be standard?
            // i.e. http://stackoverflow.com/questions/728172/are-there-multiline-comment-delimiters-in-sql-that-are-vendor-agnostic
            // [/\/\*/, { token: 'comment.quote', next: '@push' }],    // nested comment not allowed :-(
            [/\*\//, { token: 'comment.quote', next: '@pop' }],
            [/./, 'comment']
        ],
        pseudoColumns: [
            [/[$][A-Za-z_][\w@#$]*/, {
                cases: {
                    '@default': 'identifier'
                }
            }]
        ],
        numbers: [
            [/0[xX][0-9a-fA-F]*/, 'number'],
            [/[$][+-]*\d*(\.\d*)?/, 'number'],
            [/((\d+(\.\d*)?)|(\.\d+))([eE][\-+]?\d+)?/, 'number']
        ],
        strings: [
            [/N'/, { token: 'string', next: '@string' }],
            [/'/, { token: 'string', next: '@string' }]
        ],
        string: [
            [/[^']+/, 'string'],
            [/''/, 'string'],
            [/'/, { token: 'string', next: '@pop' }]
        ],
        complexIdentifiers: [
            [/\[/, { token: 'identifier.quote', next: '@bracketedIdentifier' }],
            [/"/, { token: 'identifier.quote', next: '@quotedIdentifier' }]
        ],
        bracketedIdentifier: [
            [/[^\]]+/, 'identifier.quote'],
            [/]]/, 'identifier.quote'],
            [/]/, { token: 'identifier.quote', next: '@pop' }]
        ],
        quotedIdentifier: [
            [/[^"]+/, 'identifier.quote'],
            [/""/, 'identifier.quote'],
            [/"/, { token: 'identifier.quote', next: '@pop' }]
        ],
        scopes: [
            [/BEGIN\s+(DISTRIBUTED\s+)?TRAN(SACTION)?\b/i, 'keyword'],
            [/BEGIN\s+TRY\b/i, { token: 'keyword.try' }],
            [/END\s+TRY\b/i, { token: 'keyword.try' }],
            [/BEGIN\s+CATCH\b/i, { token: 'keyword.catch' }],
            [/END\s+CATCH\b/i, { token: 'keyword.catch' }],
            [/(BEGIN|CASE)\b/i, { token: 'keyword.block' }],
            [/END\b/i, { token: 'keyword.block' }],
            [/WHEN\b/i, { token: 'keyword.choice' }],
            [/THEN\b/i, { token: 'keyword.choice' }]
        ]
    }
};

